language: php

php:
    - 7.1
    - 7.0
    - 5.6

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - composer self-update

install:
    - composer update --prefer-dist

    - tests/Application/bin/console doctrine:schema:create --env=test -vvv --no-interaction
    - tests/Application/bin/console doctrine:phpcr:repository:init --env=test -vvv --no-interaction

script:
    - composer validate

    - vendor/bin/behat --strict -vvv --no-interaction || vendor/bin/behat --strict -vvv --no-interaction --rerun
